### ISSUE TITLE
Page & Custom Post SEO Returns Null

### ISSUE THREAD

**Issue by tinytoolbox** [ashhitch/wp-graphql-yoast-seo#82] opened 2021-02-12 15:30 UTC
The plugin is exposing & returning post SEO fields but not returning field values pages or custom post types.  Why can't figure out why.

Using `4.8.0` of the plugin
Yoast version `15.3`
WPGraphQL `1.1.3`
`gatsby-source-wordpress 4.0.1`

Example Query:

```query GetPages {
  pages {
    edges {
      node {
        id
        title
        seo {
          canonical
          title
          metaDesc
          focuskw
          metaRobotsNoindex
          metaRobotsNofollow
          opengraphAuthor
          opengraphDescription
          opengraphTitle
          opengraphDescription
          opengraphImage {
            altText
            sourceUrl
            srcSet
          }
          opengraphUrl
          opengraphSiteName
          opengraphPublishedTime
          opengraphModifiedTime
          twitterTitle
          twitterDescription
          twitterImage {
            altText
            sourceUrl
            srcSet
          }
          breadcrumbs {
            url
            text
          }
          cornerstone
          schema {
            pageType
            articleType
          }
        }
      }
    }
  }
}```

**Comment by stevepepple** [comment] 2021-02-20 19:55
I'm seeing the same after updating the gatsby-source-wordpress plugin. Some pages work and other return null for the SEO field.

**Comment by ashhitch** [comment] 2021-02-22 14:55
Thanks for reporting this, Will try to look into this ASAP

**Comment by stevepepple** [comment] 2021-02-22 17:58
Follow up, I didn't realize that there was a name change to the Wordpress plugin. Once I searched for "Add WPGraphQL SEO" and upgraded to ver. 4.11, the issue was resolved. The previously plugin didn't show an update. 
![Uploading Screen Shot 2021-02-22 at 9.57.26 AM.png…]()

**Comment by ashhitch** [comment] 2021-02-22 19:02
@stevepepple  sorry had to change it to comply with WordPress plugin directory T&CS.
@tinytoolbox could you make sure you are on the latest version?

**Comment by tinytoolbox** [comment] 2021-02-24 19:19
Updating the latest version resulted in no changes.  Only queries for SEO fields on regular posts return a value.  Queries for page SEO values or values for Custom Post Types are returned `null`

**Comment by ashhitch** [comment] 2021-03-01 12:44
@tinytoolbox is your issue in WpGraphql or in the Gatsby layer?

**Comment by stevepepple** [comment] 2021-03-03 18:24
> @stevepepple sorry had to change it to comply with WordPress plugin directory T&CS.
> @tinytoolbox could you make sure you are on the latest version?

Yes, right, after I switched to the new package, it worked.

**Comment by vladderave** [comment] 2021-03-04 11:30
@ashhitch I have the same issue. Plugin returns null for posts. It's a problem on WPGraphQL layer.
Plugin - Version 4.11.0
Yoast SEO Premium - Version 15.7
WPGraphQL - Version 1.1.3

**Comment by ashhitch** [comment] 2021-03-08 21:20
Im still unable to replicate this. Could anyone provide the endpoint for me to check this?

**Comment by vladderave** [comment] 2021-03-12 13:39
@ashhitch I made research and the problem was on the Gatsby layer, not GraphQL. The problem is https://github.com/gatsbyjs/gatsby-source-wordpress-experimental
I've used an experimental version of the Gatsby-source, when I am updated to the newest version of gatsby-source-wordpress the problem is gone.

**Comment by ashhitch** [comment] 2021-03-12 15:27
Ok that's good news. I'll close this off

**Closed by ashhitch** 2021-03-12 15:27 UTC
